version: "3.8"

services:
  pangeia:
    image: pintermaciel/pangeia:0.1.0
    networks:
      - minha_rede
    environment:
      - ENV POETRY_VIRTUALENVS_CREATE=false
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.pangeia.rule=Host(`pangeia.zeuslab.app`)
        - traefik.http.routers.pangeia.entrypoints=websecure
        - traefik.http.routers.pangeia.tls.certresolver=letsencryptresolver
        - traefik.http.services.pangeia.loadBalancer.server.port=8000
        - traefik.http.services.pangeia.loadBalancer.passHostHeader=true
        - traefik.http.routers.pangeia.service=pangeia

networks:
  minha_rede:
    external: true
    name: minha_rede
